 /******************************************************************************
 *
 * Module: Dio
 *
 * File Name: Dio_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Dio Driver
 *
 * Author: Mohamed Tarek
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

   /* 
   - pin
   - mode 
   - direction   PORT_PIN_IN  - PORT_PIN_OUT
   - init value
   - Pin_Direction_changeable
   - Pin_Mode_changeable
   - Pin_ResistorMode
   */
   const Port_ConfigType Port_Configuration = {
      PORT_A_PIN_0, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //0
      PORT_A_PIN_1, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //1
      PORT_A_PIN_2, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //2
      PORT_A_PIN_3, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //3
      PORT_A_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //4
      PORT_A_PIN_5, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //5
      PORT_A_PIN_6, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //6 
      PORT_A_PIN_7, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //7
     
      PORT_B_PIN_0, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //8
      PORT_B_PIN_1, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //9
      PORT_B_PIN_2, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //10 
      PORT_B_PIN_3, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //11
      PORT_B_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //12 
      PORT_B_PIN_5, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //13
      PORT_B_PIN_6, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //14
      PORT_B_PIN_7, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //15
     
      PORT_C_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //16
      PORT_C_PIN_5, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //17
      PORT_C_PIN_6, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //18
      PORT_C_PIN_7, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //19
     
      PORT_D_PIN_0, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //20
      PORT_D_PIN_1, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //21
      PORT_D_PIN_2, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //22
      PORT_D_PIN_3, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //23
      PORT_D_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //24
      PORT_D_PIN_5, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //25
      PORT_D_PIN_6, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //26
      PORT_D_PIN_7, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //27
     
      PORT_E_PIN_0, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //28
      PORT_E_PIN_1, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //29
      PORT_E_PIN_2, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //30
      PORT_E_PIN_3, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //31
      PORT_E_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //32
      PORT_E_PIN_5, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //33
     
      PORT_F_PIN_0, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //34
      PORT_F_PIN_1, PORT_PIN_MODE_DIO, PORT_PIN_OUT, STD_ON, STD_ON, STD_ON, OFF, //35
      PORT_F_PIN_2, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //36
      PORT_F_PIN_3, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //37
      PORT_F_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, STD_OFF, STD_ON, STD_ON, PULL_UP, //38
   };